### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by mikasa-coder** [xyzhang16/tianchi-nl2sql-top1#2]
你好！看到了您的关于这个模型的论文在IEEE上发表了，祝贺！但是并没有找到您的论文实现代码。请问有开源的想法吗？能否提供一下数据集和代码（如果可以的话），想学习一下。
邮箱 klw811@163.com

**Comment by xyzhang16** [comment]
感谢关注！ 与公司有合作，代码无法开源。数据集手边没有，在实验室电脑上，人在家隔离。你可以去钉钉群问下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"KLEVY"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月2日(星期六) 中午1:00
收件人:&nbsp;"xyzhang16/tianchi-nl2sql-top1"<tianchi-nl2sql-top1@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xyzhang16/tianchi-nl2sql-top1] 代码问题 (#2)





 
你好！看到了您的关于这个模型的论文在IEEE上发表了，祝贺！但是并没有找到您的论文实现代码。请问有开源的想法吗？能否提供一下数据集和代码（如果可以的话），想学习一下。
 邮箱 klw811@163.com
